# Site settings
title: "delibae CV"
description: "delibae CV"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Hajin Bae"
resume_title:                   "AI Researcher & Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "iwdhanjin@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

# resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
# display_header_contact_info:    "false"

resume_header_intro: "<p>An adept AI Researcher and Developer immersed in the nexus of Bioinformatics and computational linguistics, particularly in advancing Protein Language Models (PLMs). I am deeply invested in the fine-tuning of Large Language Models to decipher the complex language of proteins, contributing to significant breakthroughs in understanding biological processes. My proficiency extends to multi-GPU computing, where I focus on accelerating AI workflows with advanced kernel methods</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/delibae"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
